{{- if .Values.ai.enabled }}
apiVersion: ai.opni.io/v1beta1
kind: OpniCluster
metadata:
  name: opni
  namespace: {{ include "opni.namespace" . }}
spec:
  version: v{{ .Chart.AppVersion }}
  deployLogCollector: false
  services:
    payloadReceiver:
      enabled: false
    gpuController:
      enabled: false
    inference:
      enabled: true
      pretrainedModels:
      - name: control-plane
      - name: rancher
      - name: longhorn
    metrics:
      enabled: false
  opensearch:
    name: opni
    namespace: {{ include "opni.namespace" . }}
{{- with .Values.ai.s3 }}
  s3:
    {{- toYaml . | nindent 4 }}
{{- end }}
  natsCluster:
    name: {{ include "opni.fullname" . }}
{{- end }}
